package app.auth.user

class UserExistsAlreadyException
    : RuntimeException("User already exist")
